apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-14T07:29:34Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "3153"
  uid: 30598605-a5be-4248-8c82-eb79cb7868ee
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.106.255.75
  clusterIPs:
  - 10.106.255.75
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31055
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
